SiteManagementUi/Controllers/ApartmentController.cs
using Microsoft.AspNetCore.Mvc;
using SiteManagementUi.Models.ApartmentModels;
using SiteManagementUi.Services;
using System.Collections.Generic;

namespace SiteManagementUi.Controllers
{
    public class ApartmentController : Controller
    {
        public IActionResult GetAllApartment()
        {
            List<GetApartmentModel> getApartmentModel = ApartmentService.GetAllApartments();
            return View(getApartmentModel);
        }
        //TODO: Model alacak şekilde değiştir
        public IActionResult AddApartment(AddApartmentModel apartmentModel)
        {
            if (apartmentModel.ApartmentBlock is null) { return View(); }

            //AddApartmentModel apartmentModel = new AddApartmentModel();
            //apartmentModel.ApartmentBlock = apartmentBlock;
            //apartmentModel.ApartmentFloor = apartmentFloor;
            //apartmentModel.ApartmentNo = apartmentNo;
            //apartmentModel.ApartmentType = apartmentType;
            ApartmentService.PostApartment(apartmentModel);
            ModelState.Clear();
            apartmentModel = new AddApartmentModel();
            return View(apartmentModel);
        }

        //[Route("ChangeApaertment/{id}")]
        public IActionResult ChangeApartment(int id)
        {
            if (id > 0)
            {
                GetApartmentModel getApartmentModel = ApartmentService.GetApartment(id);
                if (getApartmentModel != null)
                {
                    return View(getApartmentModel);

                }
            }
            return View();
        }

        [HttpPost]
        public IActionResult ChangeApartment(GetApartmentModel apartment)
        {
            if (apartment is not null)
            {
                ChangeApartmentSenderModel apartmentSender = new ChangeApartmentSenderModel();
                apartmentSender.ApartmentType = apartment.ApartmentType;
                apartmentSender.User_Id = apartment.User_Id;
                ApartmentService.PutApartment(apartment.ApartmentId, apartmentSender);
                return View();
            }
            return View();
        }
    }
}

SiteManagementUi/Controllers/DebtController.cs
using Microsoft.AspNetCore.Mvc;
using SiteManagementUi.Models.DebtModels;
using SiteManagementUi.Services;
using System.Collections.Generic;

namespace SiteManagementUi.Controllers
{
    public class DebtController : Controller
    {
        public IActionResult GetAllPaidDebt()
        {
            List<GetAllDebtModel> getAllDebtModel = DebtService.GetAllDebts(true);

            return View(getAllDebtModel);
        }
        public IActionResult GetAllNotPaidDebt()
        {
            List<GetAllDebtModel> getAllDebtModel = DebtService.GetAllDebts(false);

            return View(getAllDebtModel);
        }

        public IActionResult GetPaidDebtByPeriod()
        {
            return View();
        }

        public IActionResult GetPaidDebtByPeriodCheck(int debtMonth, int debtYear, bool isPaid)
        {
            if (debtMonth > 0)
            {
                List<GetAllDebtModel> debtModel = DebtService.GetAllDebtByPeriod(debtMonth, debtYear, isPaid);
                return View(debtModel);
            }
            return View();
        }
        public IActionResult GetAllDebtByUserId()
        {
            List<GetAllDebtModel> debtModel = DebtService.GetDebtByUserId(UserService.Token.Id, false);
            return View(debtModel);
        }

        public IActionResult GetNotPaidDebtByUserId()
        {
            List<GetAllDebtModel> debtModel = DebtService.GetDebtByUserId(UserService.Token.Id, true);
            return View(debtModel);
        }

        public IActionResult AddDebtToAll(AddDebtToAllModel debtModel)
        {
            if (debtModel.DebtBill < 1) { return View(); }

            //AddDebtToAllModel debtModel = new AddDebtToAllModel();
            //debtModel.DebtBill = debtBill;
            //debtModel.DebtDue = debtDue;
            //debtModel.DebtYear = debtYear;
            //debtModel.DebtMonth = debtMonth;

            DebtService.PostDebt(debtModel);
            ModelState.Clear();
            debtModel = new AddDebtToAllModel();
            return View();
        }

        public IActionResult PayDebt(int id)
        {
            PayDebtModel payDebtModel = new PayDebtModel();
            payDebtModel.id = id;
            return View(payDebtModel);
        }
        [HttpPost]
        public IActionResult PayDebt(PayDebtModel debtModel)
        {
            DebtService.PayDebtById(debtModel);
            return View();
        }
    }
}

SiteManagementUi/Controllers/LoginController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using SiteManagementUi.Entities;
using SiteManagementUi.Models;
using SiteManagementUi.Services;

namespace SiteManagementUi.Controllers
{
    public class LoginController : Controller
    {

        // GET: LoginController/Details/5
        public ActionResult GetLogin(string UserName, string Password)
        {
            LoginToken bag = new LoginToken();
            bag = UserService.GetLoginToken(UserName, Password);
            return View();
        }

    }
}

SiteManagementUi/Controllers/MessageController.cs
using Microsoft.AspNetCore.Mvc;
using SiteManagementUi.Models.MessageModels;
using SiteManagementUi.Services;
using System.Collections.Generic;

namespace SiteManagementUi.Controllers
{
    public class MessageController : Controller
    {
        public readonly int _id;
        public MessageController()
        {
            _id = UserService.Token.Id;
        }
        public IActionResult GetMessageByReciverId()
        {
            if (_id > 0)
            {
                List<GetMessageModel> getMessageModel = MessageService.GetMessageByReciverId(_id);
                return View(getMessageModel);
            }
            return View();
        }
        public IActionResult GetMessageBySenderId()
        {
            if (_id > 0)
            {
                List<GetMessageModel> getMessageModel = MessageService.GetMessageBySenderId(_id); ;
                return View(getMessageModel);
            }
            return View();
        }

        public IActionResult ReadMessage(int id)
        {
            MessageService.ReadMessage(id);

            return View();
        }

        public IActionResult AddMessage(AddMessageModel messageModel)
        {
            if (UserService.Token.Id > 0)
            {
                if (messageModel.MessageText is not null)
                {
                messageModel.Sender_Id = UserService.Token.Id;
                MessageService.PostMessage(messageModel);
                }
                return View();
            }
            return RedirectToAction("Home");
        }
    }
}

SiteManagementUi/Views/Shared/_Layout.cshtml
@using SiteManagementUi.Services
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SiteManagementUi</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SiteManagementUi</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        @if (UserService.Token is not null)//Token boş olduğunda hata almamak için önce token nesnesi oluşmuş mu diye kontrol ediyoruz
                        {
                            @if (UserService.Token.Role == "Admin")
                            {
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle text-light" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        Apartments
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                        <a class="dropdown-item" asp-area="" asp-controller="Apartment" asp-action="GetAllApartment">GetAllApartment</a>
                                        <div class="dropdown-divider"></div>
                                        <a class="dropdown-item" asp-area="" asp-controller="Apartment" asp-action="AddApartment">AddApartment</a>
                                        <div class="dropdown-divider"></div>
                                    </div>
                                </li>
                            }
                            @if (UserService.Token.Role == "Admin" || UserService.Token.Role == "User")
                            {
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle text-light" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        Debts
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                        @if (UserService.Token.Role == "Admin")
                                        {
                                            <a class="dropdown-item" asp-area="" asp-controller="Debt" asp-action="AddDebtToAll">AddDebtToAll</a>
                                            <div class="dropdown-divider"></div>
                                            <a class="dropdown-item" asp-area="" asp-controller="Debt" asp-action="GetAllPaidDebt">GetAllPaidDebt</a>
                                            <a class="dropdown-item" asp-area="" asp-controller="Debt" asp-action="GetAllNotPaidDebt">GetAllNotPaidDebt</a>
                                            <div class="dropdown-divider"></div>
                                        }
                                        <a class="dropdown-item" asp-area="" asp-controller="Debt" asp-action="GetPaidDebtByPeriod">GetPaidDebtByPeriod</a>
                                        <div class="dropdown-divider"></div>
                                        <a class="dropdown-item" asp-area="" asp-controller="Debt" asp-action="GetAllDebtByUserId">GetAllDebtByUserId</a>
                                        <a class="dropdown-item" asp-area="" asp-controller="Debt" asp-action="GetNotPaidDebtByUserId">GetNotPaidDebtByUserId</a>
                                    </div>
                                </li>
                            }
                            @if (UserService.Token.Role == "Admin" || UserService.Token.Role == "User")
                            {
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle text-light" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        Messages
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                        <a class="dropdown-item" asp-area="" asp-controller="Message" asp-action="GetMessageByReciverId">GetMessageByReciverId</a>
                                        <a class="dropdown-item" asp-area="" asp-controller="Message" asp-action="GetMessageBySenderId">GetMessageBySenderId</a>
                                        <div class="dropdown-divider"></div>
                                        <a class="dropdown-item" asp-area="" asp-controller="Message" asp-action="AddMessage">Send Message</a>

                                    </div>
                                </li>
                            }
                            @if (UserService.Token.Role == "Admin" || UserService.Token.Role == "User")
                            {
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle text-light" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        Users
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                        <a class="dropdown-item" asp-area="" asp-controller="User" asp-action="GetAllUser">GetAllUser</a>
                                        @if (UserService.Token.Role == "Admin")
                                        {
                                            <div class="dropdown-divider"></div>
                                            <a class="dropdown-item" asp-area="" asp-controller="User" asp-action="AddUser">AddUser</a>
                                        }
                                    </div>
                                </li>
                            }

                        }
                    </ul>
                    <ul class="navbar-nav navbar-right">
                        @if (UserService.Token is null)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark btn btn-light btn-small btn-nav" asp-area="" asp-controller="Login" asp-action="GetLogin">Login</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark btn btn-light btn-small btn-nav" asp-area="" asp-controller="" asp-action=""> Hoşgeldin @UserService.Token.UserFullName</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - SiteManagementUi - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>